# Generated by Django 5.0.2 on 2024-03-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassicCocktails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название коктейля')),
                ('text', models.TextField(blank=True, verbose_name='История коктейля')),
                ('photo', models.ImageField(default='default.jpg', upload_to='photos/%Y/m%/%d', verbose_name='Фото')),
                ('recept', models.CharField(max_length=255, verbose_name='Рецепт коктейля')),
            ],
            options={
                'verbose_name': 'коктейль',
                'verbose_name_plural': 'коктейли',
                'ordering': ['title'],
            },
        ),
    ]
