# Generated by Django 5.0.2 on 2024-03-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barstory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classiccocktails',
            name='recept',
            field=models.TextField(max_length=255, verbose_name='Рецепт коктейля'),
        ),
    ]
