# Generated by Django 5.0.2 on 2024-03-05 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barstory', '0002_alter_classiccocktails_recept'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classiccocktails',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='photos/image', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='classiccocktails',
            name='recept',
            field=models.TextField(blank=True, verbose_name='Рецепт коктейля'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Псевдоним')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='О пользователе')),
                ('profile_image', models.ImageField(default='profiles/user-default.png', upload_to='profiles/', verbose_name='Фото')),
                ('workplace', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка место работы')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистраци')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
