# Generated by Django 5.0.2 on 2024-03-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barstory', '0004_remove_profile_name_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profiles/icon.jpg', upload_to='profiles/', verbose_name='Фото'),
        ),
    ]
