# Generated by Django 5.0.2 on 2024-05-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barstory', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Мероприятие')),
                ('event_photo', models.ImageField(default='events.jpg', upload_to='event_photos/image', verbose_name='Фото')),
                ('event_text', models.TextField(blank=True, verbose_name='Мероприятие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('history_photo', models.ImageField(default='history.jpg', upload_to='history_photos/image', verbose_name='Фото')),
                ('short_text', models.TextField(verbose_name='Краткое описание')),
                ('text', models.TextField(verbose_name='Историяеская справка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'историю',
                'verbose_name_plural': 'Исторические справки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Новость')),
                ('new_photo', models.ImageField(default='news.jpg', upload_to='news_photos/image', verbose_name='Фото')),
                ('news_text', models.TextField(blank=True, verbose_name='Новость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='classiccocktails',
            options={'ordering': ['title'], 'verbose_name': 'коктейль', 'verbose_name_plural': 'Коктейли'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created'], 'verbose_name': 'профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
