# Generated by Django 5.0.2 on 2024-05-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barstory', '0006_events_history_news_alter_classiccocktails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='town',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок новости'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workplace',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Место работы'),
        ),
    ]
